services:
  water_system:
    build:
      context: .
    container_name: water_system
    volumes:
      - .:/app
    environment:
      - SERVER_URL=${SERVER_URL:-:8080}
      - ENVIRONMENT=${ENVIRONMENT:-development}
      - ZONES_FILE=${ZONES_FILE:-/tmp/zones.yaml}
      - AUTH_TOKEN=${AUTH_TOKEN:-token}
      - DAILY_PROGRAMS_FILE=${DAILY_PROGRAMS_FILE:-/tmp/daily_programs.yml}
      - ODD_PROGRAMS_FILE=${ODD_PROGRAMS_FILE:-/tmp/odd_programs.yml}
      - EVEN_PROGRAMS_FILE=${EVEN_PROGRAMS_FILE:-/tmp/even_programs.yml}
      - WEEKLY_PROGRAMS_FILE=${WEEKLY_PROGRAMS_FILE:-/tmp/weekly_programs.yml}
      - TEMPERATURE_PROGRAMS_FILE=${TEMPERATURE_PROGRAMS_FILE:-/tmp/temperature_programs.yml}
      - EXECUTION_LOGS_FILE=${EXECUTION_LOGS_FILE:-/tmp/execution_logs.json}
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN:-token default}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID:-12345}
      - TELEGRAM_BOT_ENABLED=${TELEGRAM_BOT_ENABLED:-false}
      - NATS_SERVER_URL=${NATS_SERVER_URL:-nats://nats:4222}
      - EVENTS_DIRECTORY=${EVENTS_DIRECTORY:-/tmp/events}
    ports:
      - "8083:8080"
    depends_on:
      - nats
    networks:
      - water_system

  nats:
    image: nats:2-alpine
    container_name: nats
    command: ["-js", "--store_dir", "/data", "--http_port", "8222"]
    ports:
      - "4222:4222"
      - "8222:8222"
    volumes:
      - nats_data:/data
    restart: unless-stopped
    networks:
      - water_system

  nats-box:
    image: synadia/nats-box:latest
    container_name: nats-box
    depends_on:
      - nats
    stdin_open: true
    tty: true
    entrypoint: ["sh", "-lc", "sleep infinity"]
    networks:
      - water_system

networks:
  water_system:
    driver: bridge

volumes:
  nats_data: