FROM golang:1.17.9-alpine

RUN mkdir /app
WORKDIR /app

RUN apk add --update --no-cache make git

RUN go install -v github.com/cespare/reflex@latest
EXPOSE 8080
ENTRYPOINT ["reflex", "-c", "./reflex.conf"]
