- hosts: raspberry_water_system
  vars:
    zones_file: "{{ home }}/zones.yaml"
    executions_file: "{{ home }}/executions.yaml"
  tasks:
    - name: Ensure that necessary files exist.
      file:
        path: "{{ item }}"
        state: file
        mode: 0755
      with_items:
        - "{{ zones_file }}"
        - "{{ executions_file }}"
    - name: Build binary
      local_action:
        module: make
        chdir: ..
        target: build
    - name: Stopping supervisor
      shell: supervisorctl stop "{{ service_name}}"
      become: yes
    - name: Copy old binary file
      shell: cp {{ binary_path }} {{ binary_path }}_old
      ignore_errors: true
    - name: Upload binary file
      copy:
        src: assets/server
        dest: "{{ binary_path }}"
        mode: 0750
        force: yes
    - name: Upload config file
      template:
        src: config/config.yml.j2
        dest: "{{ home }}/config.yml"
        mode: 0750
        force: yes
    - name: Upload supervisor conf file
      template:
        src: config/raspberry-server.conf
        dest: /etc/supervisor/conf.d/raspberry-server.conf
        mode: 0750
        force: yes
      become: yes
    - name: Reload config supervisor
      shell: supervisorctl reload
      become: yes
    - name: Start supervisor
      shell: supervisorctl start "{{ service_name}}"
      become: yes