- hosts: raspberry_water_system
  tasks:
    - name: Stopping service if service exists
      with_first_found:
        - files:
            - /etc/systemd/system/water_system.service
          skip: true
      shell: systemctl stop "{{ service_name }}"
      become: yes
    - name: Copy old binary file if exists
      with_first_found:
        - files:
          - "{{ binary_path }}"
          skip: true
      shell: cp {{ binary_path }} {{ binary_path }}_old
      become: yes
    - name: Upload binary file
      copy:
        src: assets/server
        dest: "{{ binary_path }}"
        mode: 0750
        force: yes
    - name: Create service directory if not exists
      file:
        path: "{{ systemd_path }}"
        state: directory
        owner: root
        group: root
        mode: 0755
      become: yes
    - name: Updload conf file
      template:
        src: config/water_system.conf
        dest: /etc/systemd/system/water_system.conf
        mode: 0644
        force: yes
        become: yes
    - name: Upload service file
      template:
        src: config/water_system.service
        dest: /etc/systemd/system/water_system.service
        mode: 0644
        force: yes
      become: yes
    - name: reload daemon service
      shell: systemctl daemon-reload
      become: yes
    - name: Enable service on boot
      shell: systemctl enable "{{ service_name }}"
      become: yes
    - name: Start service
      shell: systemctl start "{{ service_name }}"
      become: yes
