name: "Integration and functional Tests"
on: [push]

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Go 1.19
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
      - name: Cache Dependencies
        uses: actions/cache@v2.1.3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
      - name: Create docker network
        run: docker network create water-system
      - name: Docker compose
        run: make docker-up
      - name: Wait to docker container
        run: sleep 10
      - name: Runing infrastructure tests
        run: make test-with-infra
      - name: Runing functional tests
        run: make test-functional
