name: "Integration and functional Tests"
on: [push]

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - name: Set up Go 1.24.2
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.2
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
      - name: Cache Dependencies
        uses: actions/cache@v4
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
#       - name: Create docker network
#         run: docker network create water-system
      - name: Docker compose
        run: make docker-up
      - name: Wait to docker container
        run: sleep 10
      - name: Runing infrastructure tests
        run: make test-with-infra
      - name: Runing functional tests
        run: make test-functional
