// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package http

import "encoding/json"
import "fmt"

type ExecutionItemRequest struct {
	// Seconds corresponds to the JSON schema field "seconds".
	Seconds int `json:"seconds" yaml:"seconds" mapstructure:"seconds"`

	// Zones corresponds to the JSON schema field "zones".
	Zones []string `json:"zones" yaml:"zones" mapstructure:"zones"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ExecutionItemRequest) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if v, ok := raw["seconds"]; !ok || v == nil {
		return fmt.Errorf("field seconds in ExecutionItemRequest: required")
	}
	if v, ok := raw["zones"]; !ok || v == nil {
		return fmt.Errorf("field zones in ExecutionItemRequest: required")
	}
	type Plain ExecutionItemRequest
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = ExecutionItemRequest(plain)
	return nil
}

type ProgramItemRequest struct {
	// Executions corresponds to the JSON schema field "executions".
	Executions []ExecutionItemRequest `json:"executions" yaml:"executions" mapstructure:"executions"`

	// Hour corresponds to the JSON schema field "hour".
	Hour string `json:"hour" yaml:"hour" mapstructure:"hour"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ProgramItemRequest) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if v, ok := raw["executions"]; !ok || v == nil {
		return fmt.Errorf("field executions in ProgramItemRequest: required")
	}
	if v, ok := raw["hour"]; !ok || v == nil {
		return fmt.Errorf("field hour in ProgramItemRequest: required")
	}
	type Plain ProgramItemRequest
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = ProgramItemRequest(plain)
	return nil
}

type TemperatureItemRequest struct {
	// Programs corresponds to the JSON schema field "programs".
	Programs []ProgramItemRequest `json:"programs" yaml:"programs" mapstructure:"programs"`

	// Temperature corresponds to the JSON schema field "temperature".
	Temperature float64 `json:"temperature" yaml:"temperature" mapstructure:"temperature"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *TemperatureItemRequest) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if v, ok := raw["programs"]; !ok || v == nil {
		return fmt.Errorf("field programs in TemperatureItemRequest: required")
	}
	if v, ok := raw["temperature"]; !ok || v == nil {
		return fmt.Errorf("field temperature in TemperatureItemRequest: required")
	}
	type Plain TemperatureItemRequest
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = TemperatureItemRequest(plain)
	return nil
}

type WeeklyItemRequest struct {
	// Programs corresponds to the JSON schema field "programs".
	Programs []ProgramItemRequest `json:"programs" yaml:"programs" mapstructure:"programs"`

	// WeekDay corresponds to the JSON schema field "week_day".
	WeekDay string `json:"week_day" yaml:"week_day" mapstructure:"week_day"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *WeeklyItemRequest) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if v, ok := raw["programs"]; !ok || v == nil {
		return fmt.Errorf("field programs in WeeklyItemRequest: required")
	}
	if v, ok := raw["week_day"]; !ok || v == nil {
		return fmt.Errorf("field week_day in WeeklyItemRequest: required")
	}
	type Plain WeeklyItemRequest
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = WeeklyItemRequest(plain)
	return nil
}

// This schema defines the creation programs request
type CreateProgramsRequestJson struct {
	// Daily corresponds to the JSON schema field "daily".
	Daily []ProgramItemRequest `json:"daily,omitempty" yaml:"daily,omitempty" mapstructure:"daily,omitempty"`

	// Even corresponds to the JSON schema field "even".
	Even []ProgramItemRequest `json:"even,omitempty" yaml:"even,omitempty" mapstructure:"even,omitempty"`

	// Odd corresponds to the JSON schema field "odd".
	Odd []ProgramItemRequest `json:"odd,omitempty" yaml:"odd,omitempty" mapstructure:"odd,omitempty"`

	// Temperature corresponds to the JSON schema field "temperature".
	Temperature []TemperatureItemRequest `json:"temperature,omitempty" yaml:"temperature,omitempty" mapstructure:"temperature,omitempty"`

	// Weekly corresponds to the JSON schema field "weekly".
	Weekly []WeeklyItemRequest `json:"weekly,omitempty" yaml:"weekly,omitempty" mapstructure:"weekly,omitempty"`
}
