// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package http

import "fmt"
import "encoding/json"

// This schema defines the status response
type StatusResponseJson struct {
	// Humidity corresponds to the JSON schema field "humidity".
	Humidity float64 `json:"humidity"`

	// IsRaining corresponds to the JSON schema field "is_raining".
	IsRaining bool `json:"is_raining"`

	// SystemStartedAt corresponds to the JSON schema field "system_started_at".
	SystemStartedAt string `json:"system_started_at"`

	// Temperature corresponds to the JSON schema field "temperature".
	Temperature float64 `json:"temperature"`

	// UpdatedAt corresponds to the JSON schema field "updated_at".
	UpdatedAt *string `json:"updated_at,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *StatusResponseJson) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if v, ok := raw["humidity"]; !ok || v == nil {
		return fmt.Errorf("field humidity: required")
	}
	if v, ok := raw["is_raining"]; !ok || v == nil {
		return fmt.Errorf("field is_raining: required")
	}
	if v, ok := raw["system_started_at"]; !ok || v == nil {
		return fmt.Errorf("field system_started_at: required")
	}
	if v, ok := raw["temperature"]; !ok || v == nil {
		return fmt.Errorf("field temperature: required")
	}
	type Plain StatusResponseJson
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = StatusResponseJson(plain)
	return nil
}
