// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package http

import "encoding/json"
import "fmt"

type UpdateExecutionTemperatureRequest struct {
	// Seconds corresponds to the JSON schema field "seconds".
	Seconds int `json:"seconds" yaml:"seconds" mapstructure:"seconds"`

	// Zones corresponds to the JSON schema field "zones".
	Zones []string `json:"zones" yaml:"zones" mapstructure:"zones"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *UpdateExecutionTemperatureRequest) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if v, ok := raw["seconds"]; !ok || v == nil {
		return fmt.Errorf("field seconds in UpdateExecutionTemperatureRequest: required")
	}
	if v, ok := raw["zones"]; !ok || v == nil {
		return fmt.Errorf("field zones in UpdateExecutionTemperatureRequest: required")
	}
	type Plain UpdateExecutionTemperatureRequest
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = UpdateExecutionTemperatureRequest(plain)
	return nil
}

type UpdateProgramTemperatureRequest struct {
	// Executions corresponds to the JSON schema field "executions".
	Executions []UpdateExecutionTemperatureRequest `json:"executions" yaml:"executions" mapstructure:"executions"`

	// Hour corresponds to the JSON schema field "hour".
	Hour string `json:"hour" yaml:"hour" mapstructure:"hour"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *UpdateProgramTemperatureRequest) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if v, ok := raw["executions"]; !ok || v == nil {
		return fmt.Errorf("field executions in UpdateProgramTemperatureRequest: required")
	}
	if v, ok := raw["hour"]; !ok || v == nil {
		return fmt.Errorf("field hour in UpdateProgramTemperatureRequest: required")
	}
	type Plain UpdateProgramTemperatureRequest
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = UpdateProgramTemperatureRequest(plain)
	return nil
}

// This schema defines update an existing temperature program request
type UpdateTemperatureProgramRequestJson []UpdateProgramTemperatureRequest
