// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package http

import "encoding/json"
import "fmt"

// This schema defines the request to update a zone
type UpdateZoneRequestJson struct {
	// Name corresponds to the JSON schema field "name".
	Name string `json:"name" yaml:"name" mapstructure:"name"`

	// Relays corresponds to the JSON schema field "relays".
	Relays []int `json:"relays" yaml:"relays" mapstructure:"relays"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *UpdateZoneRequestJson) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if v, ok := raw["name"]; !ok || v == nil {
		return fmt.Errorf("field name in UpdateZoneRequestJson: required")
	}
	if v, ok := raw["relays"]; !ok || v == nil {
		return fmt.Errorf("field relays in UpdateZoneRequestJson: required")
	}
	type Plain UpdateZoneRequestJson
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = UpdateZoneRequestJson(plain)
	return nil
}
